// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           61
// Async Callback (empty):               1
// Total number of exported functions:  63

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    multisig
    (
        distributeFeesFromChildContracts
        stake
        unstake
        proposeDctSafeSetCurrentTransactionBatchStatus
        proposeMultiTransferDctBatch
        moveRefundBatchToSafe
        performAction
        sign
        upgradeChildContractFromSource
        addBoardMember
        removeUser
        slashBoardMember
        changeQuorum
        addMapping
        clearMapping
        pauseDctSafe
        unpauseDctSafe
        changeFeeEstimatorContractAddress
        changeDharitriToEthGasLimit
        changeDefaultPricePerGasUnit
        changeTokenTicker
        dctSafeAddTokenToWhitelist
        dctSafeRemoveTokenFromWhitelist
        dctSafeSetMaxTxBatchSize
        dctSafeSetMaxTxBatchBlockDuration
        dctSafeSetMaxBridgedAmountForToken
        multiTransferDctSetMaxBridgedAmountForToken
        multiTransferDctSetMaxRefundTxBatchSize
        multiTransferDctSetMaxRefundTxBatchBlockDuration
        multiTransferDctSetWrappingContractAddress
        getQuorum
        getNumBoardMembers
        getRequiredStakeAmount
        getAmountStaked
        getSlashAmount
        getSlashedTokensAmount
        getLastExecutedEthBatchId
        getLastExecutedEthTxId
        getErc20AddressForTokenId
        getTokenIdForErc20Address
        getDctSafeAddress
        getMultiTransferDctAddress
        getCurrentTxBatch
        getCurrentRefundBatch
        wasActionExecuted
        wasTransferActionProposed
        getActionIdForTransferBatch
        wasSetCurrentTransactionBatchStatusActionProposed
        getActionIdForSetCurrentTransactionBatchStatus
        signed
        userRole
        getAllBoardMembers
        getAllStakedRelayers
        getActionSignerCount
        getActionValidSignerCount
        quorumReached
        getActionLastIndex
        getActionData
        pause
        unpause
        isPaused
    )
}

dharitri_sc_wasm_adapter::empty_callback! {}
