// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    bridged_tokens_wrapper
    (
        addWrappedToken
        updateWrappedToken
        removeWrappedToken
        whitelistToken
        updateWhitelistedToken
        blacklistToken
        depositLiquidity
        wrapTokens
        unwrapToken
        getUniversalBridgedTokenIds
        getTokenLiquidity
        getChainSpecificToUniversalMapping
        getchainSpecificTokenIds
        pause
        unpause
        isPaused
    )
}

dharitri_sc_wasm_adapter::empty_callback! {}
