[package]
name = "token-module"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@elrond.com>"]
edition = "2018"
[dependencies.fee-estimator-module]
path = "../fee-estimator-module"

[dependencies.dharitri-sc]
version = "0.1.1"
[dev-dependencies.dharitri-sc-scenario]
version = "0.1.1"
